name: Sample GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Print system info
        run: |
          date
          whoami
          df -h
      - name: Run shell script
        run: bash scripts/system-info.sh
